In [18]:
%matplotlib

Using matplotlib backend: <object object at 0x000002B00723DB80>


In [19]:
import pandas as pd
import numpy as py

In [20]:
from sklearn.svm import SVC

In [21]:
from sklearn.metrics import classification_report,confusion_matrix

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
import matplotlib.pyplot as plt

In [24]:
import seaborn as sns;sns.set(font_scale=1.2)

In [25]:
from sklearn.model_selection import GridSearchCV

In [26]:
recipes=pd.read_csv('c:/recipes_muffins_cupcakes_scones.csv')

In [27]:
recipes

Type  Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0    Muffin     55    28      3       7    5              2        0     0
1    Muffin     47    24     12       6    9              1        0     0
2    Muffin     47    23     18       6    4              1        0     0
3    Muffin     45    11     17      17    8              1        0     0
4    Muffin     50    25     12       6    5              2        1     0
5    Muffin     55    27      3       7    5              2        1     0
6    Muffin     54    27      7       5    5              2        0     0
7    Muffin     47    26     10      10    4              1        0     0
8    Muffin     50    17     17       8    6              1        0     0
9    Muffin     50    17     17      11    4              1        0     0
10  Cupcake     39     0     26      19   14              1        1     0
11  Cupcake     42    21     16      10    8              3        0     0
12  Cupcake     34    17     20      20    5              2        1     0
13  Cupcake     39    13     17      19   10              1        1     0
14  Cupcake     38    15     23      15    8              0        1     0
15  Cupcake     42    18     25       9    5              1        0     0
16  Cupcake     36    14     21      14   11              2        1     0
17  Cupcake     38    15     31       8    6              1        1     0
18  Cupcake     36    16     24      12    9              1        1     0
19  Cupcake     34    17     23      11   13              0        1     0
20    Scone     29     3     46       6    0             11        0     6
21    Scone     19     3     36       3   14              7       14     5
22    Scone     20     5     52       5   10              3        0     5
23    Scone     19     6     50       5    6             10        0     3
24    Scone     19    10     51       5    0             10        0     5

In [28]:
recipes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Type           25 non-null     object
 1   Flour          25 non-null     int64 
 2   Milk           25 non-null     int64 
 3   Sugar          25 non-null     int64 
 4   Butter         25 non-null     int64 
 5   Egg            25 non-null     int64 
 6   Baking Powder  25 non-null     int64 
 7   Vanilla        25 non-null     int64 
 8   Salt           25 non-null     int64 
dtypes: int64(8), object(1)
memory usage: 1.9+ KB


In [29]:
plt.figure(figsize=(8,4))

<Figure size 1200x600 with 0 Axes>

In [30]:
sns.countplot(x=recipes['Type'])

<Axes: xlabel='Type', ylabel='count'>

In [31]:
plt.tight_layout()

In [34]:
sns.lmplot(x='Sugar',y='Butter',data=recipes,hue='Type',palette='Set1',fit_reg=False,scatter_kws={"s":70})

In [35]:
sns.pairplot(recipes,vars=['Sugar','Butter'],hue='Type',palette='Dark2')

In [36]:
sns.jointplot(x='Sugar',y='Butter',data=recipes,kind='kde')

In [37]:
plt.show()

In [38]:
x=recipes.drop('Type',axis=1)

In [39]:
y=recipes['Type']

In [40]:
kernels=['Polynomial','RBF','sigmoid' ,'Linear']

In [41]:
def getClassifier(ktype):
    if ktype==0:
        return SVC(kernel='poly',degree=8,gamma="auto")
    elif ktype==1:
        return SVC(kernel='rbf',gamma="auto")
    elif ktype==2:
        return SVC(kernel='sigmoid',gamma="auto")
    elif ktype==3:
        return SVC(kernel='linear',gamma="auto")

In [42]:
for i in range(4):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)
    svclassifier=getClassifier(i)
    svclassifier.fit(x_train,y_train)
    y_pred=svclassifier.predict(x_test)
    print("Evaluation:",kernels[i],"kernel")
    print(classification_report(y_test,y_pred))

Evaluation: Polynomial kernel
              precision    recall  f1-score   support

     Cupcake       0.67      1.00      0.80         2
      Muffin       1.00      0.67      0.80         3

    accuracy                           0.80         5
   macro avg       0.83      0.83      0.80         5
weighted avg       0.87      0.80      0.80         5

Evaluation: RBF kernel
              precision    recall  f1-score   support

     Cupcake       0.20      1.00      0.33         1
      Muffin       0.00      0.00      0.00         3
       Scone       0.00      0.00      0.00         1

    accuracy                           0.20         5
   macro avg       0.07      0.33      0.11         5
weighted avg       0.04      0.20      0.07         5

Evaluation: sigmoid kernel
              precision    recall  f1-score   support

     Cupcake       0.20      1.00      0.33         1
      Muffin       0.00      0.00      0.00         3
       Scone       0.00      0.00      0.00      

C:\Users\88697\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\88697\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\88697\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\88697\anaconda3\Lib\site-packag

In [43]:
svm_classifier=SVC(gamma='auto')

In [44]:
svm_classifier.fit(x_train,y_train)

SVC(gamma='auto')

In [45]:
svm_classifier.score(x_train,y_train)

1.0

In [46]:
param_grid={'C':[0.1,1,10,100],'gamma':[1,0.1,0.01,0.001],'kernel':['rbf','poly','sigmoid']}

In [47]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=2)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s


C:\Users\88697\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(


[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.1s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=   0.0s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   0.0s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   0.0s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   0.0s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   0.0s
[CV] END ........................C=0.1, gamma=1, kernel=poly; total time=   0.0s
[CV] END .....................C=0.1, gamma=1, kernel=sigmoid; total time=   0.0s
[CV] END .....................C=0.1, gamma=1, kernel=sigmoid; total time=   0.0s
[CV] END .....................C=0.1, gamma=1, kernel=sigmoid; total time=   0.0s
[CV] END .....................C=0.1, gamma=1, kernel=sigmoid; total time=   0.0s
[CV] END ...................

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001],
                         'kernel': ['rbf', 'poly', 'sigmoid']},
             verbose=2)

In [48]:
print(grid.best_estimator_)

SVC(C=1, gamma=0.001)


In [49]:
grid_predictions =grid.predict(x_test)

In [50]:
print(confusion_matrix(y_test,grid_predictions))

[[1 0 0]
 [0 3 0]
 [0 0 1]]


In [51]:
print(classification_report(y_test,grid_predictions))

              precision    recall  f1-score   support

     Cupcake       1.00      1.00      1.00         1
      Muffin       1.00      1.00      1.00         3
       Scone       1.00      1.00      1.00         1

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

